title: 'PSEED :: paulsoh'
description: Meet Paul

url: https://paulsoh.github.io
paginate_path: "post/page:num/"
permalink: post/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: paulsoh
   twitter: paulsoh
   email: paul@tumblbug.com

# google_analytics: "UA-58263416-1"
